### ISSUE TITLE
defaultCellStyle API

### ISSUE THREAD

**Issue by knownasilya** [protobi/workbook#2]
What's the API for the `defaultCellStyle` attribute for `writeFile`? Is that part of your js-xlsx fork or is that in the normal project. I can't find the details anywhere.

**Comment by protobi** [comment]
That's part of the protobi/js-xlsx fork, not the main branch.  Styles in general aren't exported with the main branch yet.  

The API is the same as for the `.s` attribute.  On testing just now, it seems that Excel is only paying attention to the font.name and font.sz attributes, not fill color.  

`XLSX.writeFile(workbook, OUTFILE, {defaultCellStyle: { font: { name: "Courier New", sz: 18}}});`

For other cells, you might define a constant style and reference that for other cells:

**Comment by knownasilya** [comment]
This worked for me:

``` js
defaultCellStyle: {
  font: {name: 'Arial', sz: '12'},
  fill: {
    fgColor: { rgb: 'FFFFFFFF' }
  }
}
```

Are there docs on what styles are available for the `s` attribute?

**Comment by protobi** [comment]
Not yet.  That's important to add.  For now can use the [example.js](https://github.com/protobi/workbook/blob/master/example.js) as a reference.

**Comment by knownasilya** [comment]
@protobi good enough, for now.

I don't see anything about borders, are those supported yet?

**Comment by protobi** [comment]
Sorry! Borders aren't in yet.  Shouldn't be too difficult to add now there's a framework for it. May get to that this coming week, is that sufficient for your timeline?

**Comment by knownasilya** [comment]
That's more then fine! If you need any help let me know.
